/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chair/chair.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/chair/chair.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.9}>
        <mesh geometry={nodes._lift1_me_1.geometry} material={materials.metal} />
        <mesh geometry={nodes.seat_le_1.geometry} material={materials.lether} />
        <mesh geometry={nodes.backrest_le_1.geometry} material={materials.lether} />
        <mesh geometry={nodes.base_me_1.geometry} material={materials.metal} />
        <mesh geometry={nodes._column_me_1.geometry} material={materials.metal} />
        <mesh geometry={nodes.lift2_me_1.geometry} material={materials.metal} />
        <mesh geometry={nodes.pCube11_1.geometry} material={materials.plastic} />
      </group>
    </group>
  )
}

useGLTF.preload('/chair.gltf')
